FORMAT: 1A

# RetailJS
RetailJS API is a REST-based API for RetailJS. The API will provide an interface to all data within the RetailJS system. 

The API can be served out of a sub-domain http(s)://api.yourdomain.com/ on your site or from a directory such as http(s)://www.yourdomain.com/api/

# Group Sites
Sites related resources of the **RetailJS API**

## Sites Collection [/sites]
### List all Sites [GET]
+ Response 200 (application/json)

        [{
          "_id": 52557fb5f97c493203000004, "title": "Tech Shop"
        }, {
          "_id": 5255be2582c4c39b0e000004, "title": "Book Store"
        }]

### Create a Site [POST]
+ Request (application/json)

        { "title": "Art Market" }

+ Response 201 (application/json)

        { "_id": 5255cc1f9c68d58411000005, "title": "Art Market" }

## Site [/sites/{_id}]
A single Site object with all its details

+ Parameters
    + _id (required, string, `5255cc1f9c68d58411000005`) ... Unique ID of this record.  It is a string data type representing a 12-byte BSON type. 
    
### Retrieve a Site [GET]
+ Response 200 (application/json)
    + Body

            { "_id": 5255cc1f9c68d58411000005, "title": "Art Market" }

### Update a Site [PUT]
+ Response 200

### Remove a Site [DELETE]
+ Response 204
